-- Verificação consolidada do esquema em produção (migrations 0001–0032). Somente leitura.
-- Esperado: todas as linhas PASS e "== TOTAL ==" com 25 de 25.
with checks as (
  select '0001 fundação: organizacoes, membros, auditoria' item, (select count(*) from pg_tables where schemaname='public' and tablename in ('organizacoes','organizacao_membros','auditoria')) = 3 ok
  union all select '0002 contas + vw_saldo_contas', exists (select 1 from pg_views where viewname='vw_saldo_contas')
  union all select '0004 categorias', exists (select 1 from pg_tables where schemaname='public' and tablename='categorias')
  union all select '0005 lançamentos: motor (5 funções, definer) e movimentos', (select count(*) from pg_proc where proname in ('criar_lancamento','atualizar_lancamento','efetivar_lancamento','cancelar_lancamento','excluir_lancamento') and prosecdef) = 5 and exists (select 1 from pg_tables where tablename='movimentos')
  union all select '0006/0007 negócios e pessoas nos lançamentos', (select count(*) from information_schema.columns where table_schema='public' and table_name='lancamentos' and column_name in ('negocio_id','pessoa_id','contrato_id')) = 3
  union all select '0008 contratos com as colunas do repositório', (select count(*) from information_schema.columns where table_schema='public' and table_name='contratos' and column_name in ('organizacao_id','negocio_id','pessoa_id','plano_id','codigo','valor','periodicidade','data_inicio','data_fim','dia_vencimento','status')) = 11
  union all select '0009 faturamento (colunas + funções + tabelas)', (select count(*) from information_schema.columns where table_schema='public' and table_name='contratos' and column_name in ('faturamento_automatico','faturar_desde','conta_id')) = 3 and (select count(*) from pg_proc where proname in ('faturar_contrato','gerar_faturamento_agora','gerar_faturamento_todas')) = 3 and (select count(*) from pg_tables where tablename in ('faturamentos','faturamento_execucoes')) = 2
  union all select '0011 importação', (select count(*) from pg_proc where proname in ('importar_clientes','nome_plano_importado','data_importada')) = 3
  union all select '0012 recorrências (colunas, trigger, motor com 17 parâmetros)', (select count(*) from information_schema.columns where table_schema='public' and table_name='lancamentos' and column_name in ('recorrente','periodicidade','numero_parcelas','parcela_atual','data_fim_recorrencia','lancamento_origem_id')) = 6 and exists (select 1 from pg_trigger where tgname='lancamentos_b_recorrencia') and (select count(*) from pg_proc where proname in ('criar_lancamento','atualizar_lancamento') and pronargs = 17) = 2
  union all select '0013 apps: tabelas com organizacao_id, funções e views', (select count(*) from information_schema.columns where table_schema='public' and column_name='organizacao_id' and table_name in ('carteira','apps_catalogo','transacoes_carteira')) = 3 and (select count(*) from pg_proc where proname in ('configurar_carteira','criar_app','recarregar_carteira','ativar_app')) = 4 and (select count(*) from pg_views where viewname in ('vw_carteira_resumo','vw_contratos_app')) = 2
  union all select '0030 carteira com dois saldos (dinheiro e crédito, sem taxa fixa)', (select count(*) from information_schema.columns where table_schema='public' and table_name='carteira' and column_name in ('saldo_dinheiro','saldo_credito')) = 2 and exists (select 1 from information_schema.columns where table_schema='public' and table_name='negocios' and column_name='usa_carteira') and (select count(*) from information_schema.columns where table_schema='public' and table_name='negocios' and column_name in ('tipo_saldo','taxa_conversao')) = 0
  union all select '0014 sem funções antigas do motor (só 1 assinatura de cada)', (select count(*) from pg_proc where proname in ('criar_lancamento','atualizar_lancamento')) = 2
  union all select '0014 sem objetos externos', not exists (select 1 from pg_proc where proname in ('recarregar_saldo','trigger_auditoria','atualizar_updated_at_carteira')) and not exists (select 1 from pg_views where viewname='vw_dashboard_apps') and not exists (select 1 from information_schema.columns where table_schema='public' and table_name in ('carteira','apps_catalogo','transacoes_carteira') and column_name in ('created_at','updated_at'))
  union all select '0016 notificações (tabelas, motor, view)', (select count(*) from pg_tables where schemaname='public' and tablename in ('notificacoes_config','notificacoes_log')) = 2 and (select count(*) from pg_proc where proname in ('gerar_notificacoes','processar_notificacoes','executar_notificacoes_agora','enviar_notificacao_teste')) = 4 and exists (select 1 from pg_views where viewname='vw_notificacoes')
  union all select '0018 provedor evolution (fila só para service_role)', (select count(*) from pg_proc where proname in ('notificacoes_para_envio','registrar_resultado_notificacao')) = 2 and not exists (select 1 from information_schema.routine_privileges where routine_name in ('notificacoes_para_envio','registrar_resultado_notificacao') and grantee in ('anon','authenticated','PUBLIC'))
  union all select '0023 portal do cliente (tabelas, funções, anon restrito)', (select count(*) from pg_tables where schemaname='public' and tablename in ('portal_config','portal_acessos','promocoes','indicacoes','descontos_contrato')) = 5 and (select count(*) from pg_proc where proname like 'portal\_%') >= 12 and (select count(*) from information_schema.routine_privileges where grantee='anon' and routine_name like 'portal\_%') = 2
  union all select '0024 portal servnet (login sem senha, fidelidade, chamados, status da rede)', (select count(*) from pg_tables where schemaname='public' and tablename in ('portal_status_rede','portal_solicitacoes','portal_login_tentativas')) = 3 and (select count(*) from pg_proc where proname in ('fidelidade_cartao','fidelidade_registrar_premio','portal_login_verificar','portal_vincular_servico','portal_fidelidade','portal_solicitar')) = 6 and exists (select 1 from information_schema.columns where table_name='pessoas' and column_name='data_nascimento')
  union all select '0025 recorrência fixa/parcelada (tipo_recorrencia)', exists (select 1 from information_schema.columns where table_name='lancamentos' and column_name='tipo_recorrencia') and (select count(*) from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='tipo_recorrencia') = 2 and exists (select 1 from pg_proc p where p.proname='tg_lancamentos_recorrencia' and pg_get_functiondef(p.oid) like '%tipo_recorrencia%')
  union all select '0026 baixa parcial', exists (select 1 from pg_proc where proname='baixar_parcial') and not exists (select 1 from information_schema.routine_privileges where routine_name='baixar_parcial' and grantee in ('anon','PUBLIC'))
  union all select '0027 contratos de despesa (fornecedor) + lançamento automático ao criar', exists (select 1 from information_schema.columns where table_name='contratos' and column_name='tipo_financeiro') and exists (select 1 from information_schema.columns where table_name='negocios' and column_name='categoria_despesa_id') and exists (select 1 from pg_trigger where tgname='contratos_c_faturar_ao_criar')
  union all select '0028 saldo_inicial_mes', exists (select 1 from pg_proc where proname='saldo_inicial_mes') and not exists (select 1 from information_schema.routine_privileges where routine_name='saldo_inicial_mes' and grantee in ('anon','PUBLIC'))
  union all select '0029 projeção de recorrência + edição em lote', (select count(*) from pg_proc where proname in ('projetar_lancamento','atualizar_lancamento_recorrente','gerar_proxima_parcela_projetada')) = 3 and not exists (select 1 from information_schema.routine_privileges where routine_name='gerar_proxima_parcela_projetada' and grantee in ('anon','authenticated','PUBLIC'))
  union all select '0031 projeção de contratos (derivada, sem gravar)', exists (select 1 from pg_proc where proname='projecao_contratos' and prosecdef) and not exists (select 1 from information_schema.routine_privileges where routine_name='projecao_contratos' and grantee in ('anon','PUBLIC'))
  union all select '0032 edição de data em recorrência (6 parâmetros)', (select count(*) from pg_proc where proname='atualizar_lancamento_recorrente' and pronargs = 6) = 1
  union all select 'RLS ligado em todas as tabelas públicas', (select bool_and(relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r')
)
select item, ok, case when ok then 'PASS' else 'FALHOU' end as resultado from checks
union all select '== TOTAL ==', bool_and(ok), count(*) filter (where ok) || ' de ' || count(*) || ' verificações OK' from checks
order by 1;
