-- Verificação consolidada do esquema em produção (migrations 0001–0014). Somente leitura.
-- Esperado: todas as linhas PASS e "== TOTAL ==" com 14 de 14.
with checks as (
  select '0001 fundação: organizacoes, membros, auditoria' item, (select count(*) from pg_tables where schemaname='public' and tablename in ('organizacoes','organizacao_membros','auditoria')) = 3 ok
  union all select '0002 contas + vw_saldo_contas', exists (select 1 from pg_views where viewname='vw_saldo_contas')
  union all select '0004 categorias', exists (select 1 from pg_tables where schemaname='public' and tablename='categorias')
  union all select '0005 lançamentos: motor (5 funções, definer) e movimentos', (select count(*) from pg_proc where proname in ('criar_lancamento','atualizar_lancamento','efetivar_lancamento','cancelar_lancamento','excluir_lancamento') and prosecdef) = 5 and exists (select 1 from pg_tables where tablename='movimentos')
  union all select '0006/0007 negócios e pessoas nos lançamentos', (select count(*) from information_schema.columns where table_schema='public' and table_name='lancamentos' and column_name in ('negocio_id','pessoa_id','contrato_id')) = 3
  union all select '0008 contratos com as colunas do repositório', (select count(*) from information_schema.columns where table_schema='public' and table_name='contratos' and column_name in ('organizacao_id','negocio_id','pessoa_id','plano_id','codigo','valor','periodicidade','data_inicio','data_fim','dia_vencimento','status')) = 11
  union all select '0009 faturamento (colunas + funções + tabelas)', (select count(*) from information_schema.columns where table_schema='public' and table_name='contratos' and column_name in ('faturamento_automatico','faturar_desde','conta_id')) = 3 and (select count(*) from pg_proc where proname in ('faturar_contrato','gerar_faturamento_agora','gerar_faturamento_todas')) = 3 and (select count(*) from pg_tables where tablename in ('faturamentos','faturamento_execucoes')) = 2
  union all select '0011 importação', (select count(*) from pg_proc where proname in ('importar_clientes','nome_plano_importado','data_importada')) = 3
  union all select '0012 recorrências (colunas, trigger, motor com 17 parâmetros)', (select count(*) from information_schema.columns where table_schema='public' and table_name='lancamentos' and column_name in ('recorrente','periodicidade','numero_parcelas','parcela_atual','data_fim_recorrencia','lancamento_origem_id')) = 6 and exists (select 1 from pg_trigger where tgname='lancamentos_b_recorrencia') and (select count(*) from pg_proc where proname in ('criar_lancamento','atualizar_lancamento') and pronargs = 17) = 2
  union all select '0013 apps: tabelas com organizacao_id, funções e views', (select count(*) from information_schema.columns where table_schema='public' and column_name='organizacao_id' and table_name in ('carteira','apps_catalogo','transacoes_carteira')) = 3 and (select count(*) from pg_proc where proname in ('configurar_carteira','criar_app','recarregar_carteira','ativar_app')) = 4 and (select count(*) from pg_views where viewname in ('vw_carteira_resumo','vw_contratos_app')) = 2
  union all select '0013 apps: tipo_saldo como enum e sem padrão', exists (select 1 from information_schema.columns where table_schema='public' and table_name='negocios' and column_name='tipo_saldo' and udt_name='tipo_saldo_app' and column_default is null)
  union all select '0014 sem funções antigas do motor (só 1 assinatura de cada)', (select count(*) from pg_proc where proname in ('criar_lancamento','atualizar_lancamento')) = 2
  union all select '0014 sem objetos externos', not exists (select 1 from pg_proc where proname in ('recarregar_saldo','trigger_auditoria','atualizar_updated_at_carteira')) and not exists (select 1 from pg_views where viewname='vw_dashboard_apps') and not exists (select 1 from information_schema.columns where table_schema='public' and table_name in ('carteira','apps_catalogo','transacoes_carteira') and column_name in ('created_at','updated_at'))
  union all select 'RLS ligado em todas as tabelas públicas', (select bool_and(relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r')
)
select item, ok, case when ok then 'PASS' else 'FALHOU' end as resultado from checks
union all select '== TOTAL ==', bool_and(ok), count(*) filter (where ok) || ' de ' || count(*) || ' verificações OK' from checks
order by 1;
