export interface PortalConfig { id: string; organizacao_id: string; negocio_id: string; ativo: boolean; logo_url: string | null; cor_primaria: string; texto_promocional: string | null; chave_pix: string | null; instrucoes_pagamento: string | null; beneficio_indicacao: number; tema: 'escuro' | 'claro'; whatsapp_suporte: string | null; beneficio_tipo: 'valor' | 'mes_gratis'; fidelidade_ativa: boolean; site_url: string | null }
export type DadosPortalConfig = Omit<PortalConfig, 'id' | 'organizacao_id' | 'negocio_id'>
export interface PromocaoAdmin { id: string; organizacao_id: string; negocio_id: string; plano_id: string | null; titulo: string; descricao: string; regras: string | null; como_aderir: string | null; data_inicio: string; data_fim: string | null; ativa: boolean }
export type DadosPromocao = Omit<PromocaoAdmin, 'id' | 'organizacao_id'>
export interface IndicacaoAdmin { id: string; negocio_id: string; indicador_pessoa_id: string; nome_indicado: string; telefone_indicado: string; indicado_pessoa_id: string | null; status: 'pendente' | 'convertida' | 'cancelada'; beneficio_valor: number; observacao: string | null; criado_em: string }
export interface AcessoPortal { id: string; pessoa_id: string; pessoa: string; codigo_indicacao: string; criado_em: string; indicacoes: number }
export type StatusRede = 'ok' | 'lentidao' | 'queda' | 'manutencao'
export interface StatusRedeAdmin { id: string; negocio_id: string; status: StatusRede; titulo: string | null; descricao: string | null; atualizado_em: string }
export interface SolicitacaoAdmin { id: string; negocio_id: string; pessoa_id: string; pessoa: string; negocio: string; tipo: 'suporte' | 'fatura' | 'duvida' | 'upgrade'; descricao: string | null; protocolo: string; status: 'aberta' | 'em_andamento' | 'concluida'; resposta: string | null; criado_em: string }
export const ROTULO_REDE: Record<StatusRede, string> = { ok: 'Operando normalmente', lentidao: 'Lentidão', queda: 'Queda', manutencao: 'Manutenção programada' }
